SDK-9849 Swift Conversion && iOS 14 Version Bump
TheLevelUp/LUKeychainAccess pull request #30
Opened 2022-10-18 10:26 UTC by stevencuy

Functionality Scratch Draft PR

*In the process of editing this description* 

Mind dump: 

- Requires formatting and documentation
- No Throws for Obj-C compatibility, in these cases either nil or false is returned
- Considered making a HashableType wrapper but hard to do without access to generics 
- Unable to throw swift exceptions as it then is not Obj-c compatible 
- Unsure how to handle the foundation exports

2022-10-20 14:38 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +  public func recursivelyFindObject(for key: String, from aClass: AnyHashable) -> Any? {
Having issues with AnyHashable representing what used to be the class type without using generics and also having it working in a hashed collection like the set used below

2022-10-20 20:12 UTC, Xeaza requested changes
Welp. Initially I for some reason thought this project was just 1 (albeit large) file in the SDK... Alas, it's this whole project... Given all of that, nicely done so far! There's a lot here. 
I'm curious about the Set/other data structure to keep a unique list of classes used.

2022-10-20 20:12 UTC, Xeaza commented on Gemfile
> +ruby '3.1.0'
Lets make sure we match the ruby version in [ruby-version](https://github.com/TheLevelUp/whitelabel-ios-ui-sdk/blob/develop/.ruby-version) so as many of our services as possible are on the same version of ruby.

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainAccess.h
> -//  Created by Costa Walcott on 5/15/15.
😭

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/NSKeyedUnarchiverExtension.swift
> +        assertionFailure("NSKeyedUnarchiver encountered an error")
Do we have access to an `Error` here to give more context if an error happens?

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/NSKeyedUnarchiverExtension.swift
> +  class func lu_archiveObject(of aClass: AnyHashable, with data: Data)  -> Any? {
I might be missing something, but where is this method in the objc class? 
I see `lu_unarchiveObjectWithData` but the names (obviously don't match haha). Since that's deprecated but still around it looks like it's kept for safety right? Ot make sure we unarchive a thing the old way if we can and re-archive the new way. If we change the method name, doesn't that break?

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/NSKeyedArchiver+Additions.m
> -  if (@available(iOS 11, *)) {
Bye 📱 1️⃣1️⃣

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/NSKeyedArchiverExtension.swift
> +    if let data = try? archivedData(withRootObject: object, requiringSecureCoding: false) {
Same error question here. Do we potentially have better info on error output?

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainServices.swift
> +  internal var service: String?
Properties/functions should be organized by access type

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainServices.swift
> +//// A wrapper for Keychain Services using the Facade pattern: http://en.wikipedia.org/wiki/Facade_pattern
👀

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainServices.swift
> +  public class var keychainServices: LUKeychainServices {
Is this to keep backwards compatibility?

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainServices.swift
> +    guard status == noErr , let data = cfResult as? Data else {
The only thing I'm seeing not here is the line 
`id data = CFBridgingRelease(cfResult);`
Does your guard statement need to read `let data = CFBridgingRelease(cfResult)`?

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainServices.swift
> +    let updateQuery =
What's actually being updated here? It looks like the given `data` is being added to the original `query` and the `updateQuery`... This is also happening in the objc method, but I'm just curious how this is updating anything...

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainAccess.swift
> +  @objc (objectForKey:ofClass:)
Is is worth including this comment here still? https://github.com/TheLevelUp/LUKeychainAccess/pull/30/files?diff=unified&w=0#diff-6b37a1090ca36d92b4ed25c74c7d2318f2b54bc384666660f7098aa700732ad9L44
It seems like it provides some useful context.

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainAccess.swift
> +  @objc @discardableResult
I've only just started using `@discardableResult`. I like it, it can be handy!

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainAccess.swift
> +      if recursivelyFindObject(for: key, from: hashableType) == nil && string(for: key) == nil {
damn. this if statement in swift is approx 1million times easier to read than the objc version haha

2022-10-20 20:12 UTC, Xeaza commented on LUKeychainAccess/LUKeychainAccess.swift
> +  public func recursivelyFindObject(for key: String, from aClass: AnyHashable) -> Any? {
Do we have to use a `Set`? That's what is requiring the `AnyHashable` type here, right? 
I tried [an idea](https://github.com/TheLevelUp/LUKeychainAccess/tree/SDK-9849-taylor) using a Dictionary with the class name as a string as the key and the type as the value. 
Using the dictionary and using the class name as the key should keep the uniqueness by class. 
The tests are quite not happy - but I'm not sure if that's my change for just the overall swift changes and old tests

2022-10-21 06:38 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +  public func recursivelyFindObject(for key: String, from aClass: AnyHashable) -> Any? {
Yeah I was wondering about using `identifier` in this case. Probably what will be safest but definitely gotta check the backwards compatibility for Obj-c. Let me try

2022-10-21 06:42 UTC, stevencuy commented on Gemfile
> +ruby '3.1.0'
Updated to 3.0.1 as what we use currently

2022-10-21 06:42 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.h
> -//  Created by Costa Walcott on 5/15/15.
Costa who?

2022-10-21 06:44 UTC, stevencuy commented on LUKeychainAccess/NSKeyedUnarchiverExtension.swift
> +        assertionFailure("NSKeyedUnarchiver encountered an error")
(https://developer.apple.com/documentation/foundation/nskeyedunarchiver/2963379-unarchivedobject)

Yep it does, let me capture that and print it

2022-10-21 06:47 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +  @objc @discardableResult
Indeed, less warnings for sure

2022-10-21 06:47 UTC, stevencuy commented on LUKeychainAccess/NSKeyedArchiverExtension.swift
> +    if let data = try? archivedData(withRootObject: object, requiringSecureCoding: false) {
See previous answer, will update to capture the thrown error

2022-10-21 06:47 UTC, stevencuy commented on LUKeychainAccess/NSKeyedUnarchiverExtension.swift
> +  class func lu_archiveObject(of aClass: AnyHashable, with data: Data)  -> Any? {
This...just shouldn't be here haha. Its just wrong being here

2022-10-21 06:49 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +  @objc (objectForKey:ofClass:)
Yes, I'll add back the context as I want to write comments for all the public facing classes, functions and properties

2022-10-21 10:01 UTC, stevencuy commented on LUKeychainAccess/ClassIdentifier.swift
> +// THIS WILL BE REMOVED, UNLESS SWIFT SPECIFIC (@nonobjc) functions will be added
I made this class to experiment with using an identifier of sorts to hash instead. As you stated this would require always checking for existing hashes based upon the class type, unarchiving the data and re-archive as this hash. 

It works for swift types (not just classes) but see the note below about adopting / using custom types.

2022-10-21 10:03 UTC, stevencuy commented on LUKeychainAccess/LUKeychainArchiveError.swift
> +  case unexpectedType(object: Any, key: AnyHashable, expectedType: Any.Type)
If we are to make @nonobjc functions in addition to the @Objc ones, we can then throw errors and specify them properly here. Wouldn't be much additional work honestly but there's plenty left in tests still.

2022-10-21 10:05 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +      // throw LUKeychainUnarchiveError.unexpectedType(object: object, key: key, expectedType: NSNumber.self)
Example usage of throwing that we could bubble up only to the @nonobjc functions

2022-10-21 10:07 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +  public func set(double: Double, for key: String) -> Bool {
These have been updated to return a discardable Bool for success. As I can't throw obj-c exceptions just checking for a Bool is a quick success check. Ideally we'd be using @nonobjc throw / try blocks

2022-10-21 10:09 UTC, stevencuy commented on LUKeychainAccess/LUKeychainAccess.swift
> +  public func object(for key: String, ofClasses classes: [AnyClass]) -> Any? {
This has been updated to use the array so we don't care about AnyHashable anymore. Note this may have issues for Swift types like "String" that are not AnyClass (i.e. AnyObject.Type) because they are structs.

2025-01-27 14:17 UTC, closed without merging